### ISSUE TITLE
Tracking: Documentation

### ISSUE THREAD

**Issue by radiohazard-dev** [radiohazard-dev/the-diddy#10]
Write documentation on 
- [ ] commands, including their inputs, format, and expected output
- [ ] how configuration works
- [ ] where what files are expected to be and why
- [ ] miscellaneous features
